#!/bin/sh
# This script is executed once after the module is installed by JeVois if it was added to the jevois/packages/ directory
# of the microSD card as a .jvpkg file. The script is deleted from the microSD card after execution.
#
# The caller script will set the current directory to the location of this script before launching the script.

# Add our video mappings to the main mappings file:
jevois-add-videomapping YUYV 320 240 30 YUYV 320 240 30 OliverDunbabin HarrisCorner
jevois-add-videomapping NONE 0 0 0 YUYV 320 240 28.3 OliverDunbabin HarrisCorner
jevois-add-videomapping YUYV 640 480 7.0 YUYV 640 480 7.0 OliverDunbabin HarrisCorner
jevois-add-videomapping NONE 0 0 0 YUYV 640 480 7.0 OliverDunbabin HarrisCorner

# Example of a simple message:
echo "HarrisCorner is now installed"

